name: BinaryClock
author: thinkphp
current: v1.0  
category: widgets  
tags: [time,clock,binary,periodical,tobin]
docs: http://github.com/thinkphp/BinaryClock/blob/master/Docs/BinaryClock.md 
demo: http://thinkphp.github.com/BinaryClock/ 
